"""
ViewSets for Project and Task.

ProjectViewSet — full CRUD + soft-delete + trash + restore + hard-delete
TaskViewSet    — full CRUD + soft-delete + trash + restore + hard-delete
                 also supports filtering by project via ?project=<id>

Every non-standard action is decorated with @action and appears under
/api/projects/<id>/restore/, /api/projects/trash/, etc.
"""

from django.shortcuts import get_object_or_404
from django.utils import timezone
from datetime import timedelta

from rest_framework import viewsets, status
from rest_framework.decorators import action
from rest_framework.response import Response

from .models import Project, Task
from .serializers import ProjectSerializer, TaskSerializer


TRASH_WINDOW = timedelta(hours=24)


# ---------------------------------------------------------------------------
# Project ViewSet
# ---------------------------------------------------------------------------

class ProjectViewSet(viewsets.ModelViewSet):
    """
    Standard endpoints (auto-generated by the Router):

        GET    /api/projects/             → list active projects
        POST   /api/projects/             → create project (+ optional tasks)
        GET    /api/projects/{id}/        → retrieve project (tasks nested)
        PUT    /api/projects/{id}/        → full update
        PATCH  /api/projects/{id}/        → partial update
        DELETE /api/projects/{id}/        → soft delete

    Custom endpoints (@action):

        GET    /api/projects/trash/              → list soft-deleted (< 24 h)
        POST   /api/projects/{id}/restore/       → undo soft delete
        DELETE /api/projects/{id}/hard-delete/   → permanent removal
    """

    queryset = Project.objects.all()   # SoftDeleteManager hides deleted rows
    serializer_class = ProjectSerializer

    # -- Override destroy → soft delete instead of hard delete ---------------

    def destroy(self, request, *args, **kwargs):
        obj = self.get_object()
        obj.delete()                   # soft delete (see SoftDeleteModel)
        return Response(status=status.HTTP_204_NO_CONTENT)

    # -- Trash list ----------------------------------------------------------

    @action(detail=False, methods=["get"], url_path="trash")
    def trash(self, request):
        """Return all soft-deleted projects still within the recovery window."""
        cutoff = timezone.now() - TRASH_WINDOW
        qs = Project.all_objects.filter(
            is_deleted=True,
            deleted_at__gte=cutoff,
        )
        serializer = self.get_serializer(qs, many=True)
        return Response(serializer.data)

    # -- Restore -------------------------------------------------------------

    @action(detail=True, methods=["post"], url_path="restore")
    def restore(self, request, pk=None):
        """Restore a soft-deleted project if still within the 24-hour window."""
        obj = get_object_or_404(Project.all_objects, pk=pk, is_deleted=True)
        if not obj.is_recoverable:
            return Response(
                {"error": "Recovery window expired — this project cannot be restored."},
                status=status.HTTP_400_BAD_REQUEST,
            )
        obj.restore()
        return Response(self.get_serializer(obj).data)

    # -- Hard delete ---------------------------------------------------------

    @action(detail=True, methods=["delete"], url_path="hard-delete")
    def hard_delete(self, request, pk=None):
        """Permanently remove a project (and its tasks) from the database."""
        obj = get_object_or_404(Project.all_objects, pk=pk)
        obj.delete(hard=True)
        return Response(status=status.HTTP_204_NO_CONTENT)


# ---------------------------------------------------------------------------
# Task ViewSet
# ---------------------------------------------------------------------------

class TaskViewSet(viewsets.ModelViewSet):
    """
    Standard endpoints:

        GET    /api/tasks/            → list active tasks (filter: ?project=<id>)
        POST   /api/tasks/            → create task
        GET    /api/tasks/{id}/       → retrieve task
        PUT    /api/tasks/{id}/       → full update
        PATCH  /api/tasks/{id}/       → partial update (e.g. toggle is_done)
        DELETE /api/tasks/{id}/       → soft delete

    Custom endpoints:

        GET    /api/tasks/trash/             → trash bin (< 24 h)
        POST   /api/tasks/{id}/restore/      → undo soft delete
        DELETE /api/tasks/{id}/hard-delete/  → permanent removal
    """

    serializer_class = TaskSerializer

    def get_queryset(self):
        qs = Task.objects.all()  # default manager hides deleted rows
        project_id = self.request.query_params.get("project")
        if project_id:
            qs = qs.filter(project_id=project_id)
        return qs

    def destroy(self, request, *args, **kwargs):
        self.get_object().delete()
        return Response(status=status.HTTP_204_NO_CONTENT)

    @action(detail=False, methods=["get"], url_path="trash")
    def trash(self, request):
        cutoff = timezone.now() - TRASH_WINDOW
        qs = Task.all_objects.filter(is_deleted=True, deleted_at__gte=cutoff)
        project_id = request.query_params.get("project")
        if project_id:
            qs = qs.filter(project_id=project_id)
        return Response(self.get_serializer(qs, many=True).data)

    @action(detail=True, methods=["post"], url_path="restore")
    def restore(self, request, pk=None):
        obj = get_object_or_404(Task.all_objects, pk=pk, is_deleted=True)
        if not obj.is_recoverable:
            return Response(
                {"error": "Recovery window expired — this task cannot be restored."},
                status=status.HTTP_400_BAD_REQUEST,
            )
        obj.restore()
        return Response(self.get_serializer(obj).data)

    @action(detail=True, methods=["delete"], url_path="hard-delete")
    def hard_delete(self, request, pk=None):
        obj = get_object_or_404(Task.all_objects, pk=pk)
        obj.delete(hard=True)
        return Response(status=status.HTTP_204_NO_CONTENT)
